<%@ Page Language="C#" Title="Do Not Email List" AutoEventWireup="true" CodeFile="DoNotEmailList.aspx.cs"
    Inherits="BWA.Knowledgebase.DoNotEmailList" MasterPageFile="~/MasterPage.master"
    meta:resourcekey="PageResource1" %>

<asp:Content ID="Content1" ContentPlaceHolderID="PageBody" runat="Server">
    <asp:ObjectDataSource ID="ObjectDataSourceDoNotEmailList" runat="server"
        OnSelecting="ObjectDataSourceDoNotEmailList_Selecting" DeleteMethod="Delete" SelectMethod="GetData"
        TypeName="MainDataSetTableAdapters.DoNotEmailTableAdapter">
        <SelectParameters>
            <asp:Parameter DbType="Guid" Name="InstanceId" />
        </SelectParameters>
        <DeleteParameters>
            <asp:Parameter DbType="Guid" Name="DoNotEmailId" />
        </DeleteParameters>
    </asp:ObjectDataSource>
    <mits:CommonGridView ID="GridDoNotEmailList" runat="server" AllowPaging="True" AutoGenerateColumns="False"
        ColorScheme="TanGray" DataKeyNames="DoNotEmailId" AutoGenerateDeleteButton="true" DataSourceID="ObjectDataSourceDoNotEmailList"
        Width="300px" PageSize="100">
        <Columns>
            <asp:BoundField DataField="Email" HeaderText="Email" ReadOnly="True" />
        </Columns>
    </mits:CommonGridView>
</asp:Content>
